### ISSUE TITLE
Usage with a probot client

### ISSUE THREAD

**Issue by zeke** [gr2m/octokit-create-pull-request#16]
Hey @gr2m 👋 

I remember you saying you'd make this plugin someday. And you did!

I'd like to use this in a probot app with the `context.github` client. Is that possible?

If not, is there a way to instantiate a new octokit/rest.js client that borrows the credentials from the existing `context.github` client?

**Comment by gr2m** [comment]
I think that issue would be better placed in the Probot repository. The `context.github` already has several plugins loaded so you really want to re-use that, especially the retry/throttling plugins will be important for this one. 

There is a way to pass a custom Octokit instance to Probot ... but I'd have to research it myself, I remember someone else got it working, it should be in the probot/probot issues somewhere. Let me know if you can't find it, I can have a look myself, too

**Comment by zeke** [comment]
https://github.com/probot/probot/issues/531 is related, but seems pretty inconclusive.

Looking at https://github.com/gr2m/octokit-create-pull-request/blob/master/lib/create-pull-request.js, I think this might work as an alternative to modifying probot's rest.js client:

```js
const createPullRequest = require('octokit-create-pull-request/lib/create-pull-request')

module.exports = (app) => {
  app.on('some-event', async context => {
    await createPullRequest(
      context.github,
      { owner, repo, title, body, base, head, changes }
    )
  })
}
```

**Comment by gr2m** [comment]
This is the one I was thinking about:
https://github.com/probot/probot/pull/840

But I never used it myself.

> `const createPullRequest = require('octokit-create-pull-request/lib/create-pull-request')`

Yeah that should work 👍

**Comment by zeke** [comment]
Ah, nice! https://github.com/Eddman/probot/blob/b2fb00809236316e0f51eb8b5136bea53b6a9457/test/index.test.js#L299-L316

Thanks for digging that up. ❤️
